### ISSUE TITLE
Intellectual property infringement

### ISSUE THREAD

**Issue by gtworek** [alexnimo/Nimo-Awesome_repo#1]
Hello! 
The link you publish in your repo, contains the whitepaper including my tool, without mentioning me as an author. I see the value of such documents, so I am not asking you to delete it, but if you put "the whitepaper describes CQRDCache tool without mentioning Grzegorz Tworek as an author" it will be enough for me. Thank you in advance!
The link: https://i.blackhat.com/asia-19/Thu-March-28/bh-asia-Januszkiewicz-CQTools-New-Ultimate-Hacking-Toolkit-wp.pdf

**Comment by alexnimo** [comment]
Hi, no problem at all!
Done!

**Comment by alexnimo** [comment]
done
